pipeline {
    agent any
    stages {
        stage('node pipeline') {
            agent {
                docker {
                    image 'node:20.11.1-alpine3.19'
                    reuseNode true
                }
            }
            stages {
                stage('checkout') {
                    steps {
                        echo "hola mundo"
                    }
                }
                stage('install') {
                    steps {
                        sh "npm install"
                    }
                }
                stage('test') {
                    steps {
                        sh "npm run test"}
                }
                stage('build') {
                    steps {
                        sh "npm run build"
                    }
                }
            }
        }
        stage('build docker') {
            steps {
                script {
                    docker.withRegistry('http://localhost:8082', 'nexis-key') {
                    sh "docker build -t localhost:8082/mi-proyecto-devops ."
                    sh "docker tag localhost:8082/mi-proyecto-devops localhost:8082/mi-proyecto-devops:${env.BUILD_NUMBER}"
                    sh "docker push localhost:8082/mi-proyecto-devops"
                    sh "docker push localhost:8082/mi-proyecto-devops:${env.BUILD_NUMBER}"
                    }
                }
            }
        }
    }
}
